jobs:
  include:
  - stage: test
    language: elixir
    elixir: 1.7.4

    services:
    - postgresql

    git:
      submodules: false

    otp_release: 21.2.2

    before_script:
    - mix do ecto.create, ecto.migrate

    script:
    - mix test

    install:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get

  - stage: deploy
    language: minimal
    services:
    - docker
    before_deploy: chmod +x heroku-deploy.sh
    deploy:
    - provider: script
      script:  ./heroku-deploy.sh
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^master$
